name: Update yarn version for release
description: |
  Updates yarn version which automatically does a commit and this action tags

inputs:
  repository_dir:
    description: 'Directory of repository to update'
    required: true

runs:
  using: composite
  steps:
    - name: Update yarn version and tag
      shell: bash
      working-directory: ${{ inputs.repository_dir }}
      env:
        SKIP_TAG: ${{ inputs.skip_tag }}
      run: |
        yarn install --frozen-lockfile
        yarn config set version-git-tag false
        yarn version --new-version $RELEASE
        git commit --allow-empty -am "Update version to $RELEASE"
        git tag --force $RELEASE_TAG
