name: Update package version for release
description: |
  Updates package version which automatically does a commit and this action tags

inputs:
  repository_dir:
    description: 'Directory of repository to update'
    required: true
  skip_tag:
    description: 'Skip git tag'
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Update version and tag
      shell: bash
      working-directory: ${{ inputs.repository_dir }}
      env:
        SKIP_TAG: ${{ inputs.skip_tag }}
      run: |
        pnpm install --frozen-lockfile
        pnpm config set version-git-tag false
        pnpm version --new-version $RELEASE
        git commit --allow-empty -am "Update version to $RELEASE"
        if [ "$SKIP_TAG" == "false" ]; then
          echo "Tagging version $RELEASE"
          git tag $RELEASE
        fi
