name: Setup PASS Java project

runs:
  using: composite
  steps:
    - name: Config git user
      run: |
        git config user.name ${{ github.actor }}
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Setup Java & Maven
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE