name: "Publish to SNS Topic: Triggers Deployment to AWS"

on:
  workflow_call:
    inputs:
      DEPLOYMENT_ENVIRONMENT:
        description: 'Environment'
        type: string
        required: true
      targetCommitRef:
        description: 'Commit ref to deploy'
        type: string
        default: 'main'
    secrets:
      AWS_REGION:
        required: true
      AWS_TOPIC_ARN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
    inputs:
      DEPLOYMENT_ENVIRONMENT:
        type: choice
        description: 'Environment'
        options:
        - demo
        - development
        required: true
      targetCommitRef:
        description: 'Commit ref to deploy'
        default: 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install boto3
      - name: Run Python SNS Publish Script
        working-directory: ${{ github.workspace }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_TOPIC_ARN: ${{ secrets.AWS_TOPIC_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOYMENT_ENVIRONMENT: ${{ inputs.DEPLOYMENT_ENVIRONMENT }}
          TARGET_COMMIT_REF: ${{ inputs.targetCommitRef }}
        run: python tools/aws_sns_publish_topic.py
