name: "Publish: Manual Full Release All Eclipse-PASS Projects"

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version (e.g. 0.1.0)'
        required: true
      nextversion:
        description: 'Next dev version (e.g. 0.2.0-SNAPSHOT)'
        required: true
      runtests:
        description: 'Run acceptance tests against release version before pushing images?'
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-java-release:
    uses: ./github/workflows/pass-java-release.yml@main # Should version these workflows
    with:
      releaseversion: ${{ inputs.releaseversion }}
      nextversion: ${{ inputs.nextversion }}
    secrets:
      MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

  run-pass-ui-release:
    uses: eclipse-pass/pass-ui/.github/workflows/release.yml@main
    with:
      releaseversion: ${{ inputs.releaseversion }}
      nextversion: ${{ inputs.nextversion }}

  run-pass-auth-release:
    uses: eclipse-pass/pass-auth/.github/workflows/release.yml@main
    with:
      releaseversion: ${{ inputs.releaseversion }}
      nextversion: ${{ inputs.nextversion }}

  run-pass-acceptance-testing-release:
    uses: eclipse-pass/pass-acceptance-testing/.github/workflows/release.yml@main
    with:
      releaseversion: ${{ inputs.releaseversion }}
      nextversion: ${{ inputs.nextversion }}

  run-pass-docker-release:
    needs: 
      - 'run-java-release'
      - 'run-pass-ui-release'
      - 'run-pass-auth-release'
      - 'run-pass-acceptance-testing-release'
    uses: eclipse-pass/pass-docker/.github/workflows/release.yml@main
    with:
      releaseversion: ${{ inputs.releaseversion }}
      nextversion: ${{ inputs.nextversion }}
      runtests: ${{ inputs.runtests }}

  run-deploy-release-to-aws-demo:
    needs: 
      - 'run-pass-docker-release'
    uses: .github/workflows/deployToAWS.yml@main
    with:
      DEPLOYMENT_ENVIRONMENT: demo
      targetCommitRef: ${{ inputs.releaseversion }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_TOPIC_ARN: ${{ secrets.AWS_TOPIC_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
