name: "Publish: manual full release OR automatic snapshot"

on: workflow_dispatch

jobs:
  deploy_code:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Check users available
        run: |
          echo "Using OSSRH_USERNAME ${{ secrets.OSSRH_USERNAME }}"
          echo "Using GH_USER ${{ secrets.GH_USER }}"

      - name: Config git user
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: DRYRUN -- Release main POM
        run: |
          mvn -B -U -V -ntp release:prepare -DreleaseVersion=0.0 -Dtag=0.0 -DdevelopmentVersion=0.0 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          mvn -B -U -V -ntp release:perform -P release -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAMEX }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORDX }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASEX }}
